import { Router, type IRouter } from "express";
import healthRouter from "./health";
import quotesRouter from "./quotes";
import businessProfileRouter from "./business-profile";
import paymentsRouter from "./payments";
import storageRouter from "./storage";
import adminRouter from "./admin";
import catalogRouter from "./catalog";
import whatsappRouter from "./whatsapp";
import clientsRouter from "./clients";
import documentsRouter from "./documents";
import crmRouter from "./crm";
import supportRouter from "./support";
import publicQuotesRouter from "./public-quotes";
import speechRouter from "./speech";
import cronRouter from "./cron";
import notificationsRouter from "./notifications";
import contractsRouter from "./contracts";
import signRouter from "./sign";
import jobsRouter from "./jobs";
import costsRouter from "./costs";
import teamRouter from "./team";
import teamMembersRouter from "./team-members";
import workerTimeRouter from "./worker-time";
import crewRouter from "./crew";
import complianceRouter from "./compliance";
import booksRouter from "./books";
import invoicesRouter from "./invoices";
import invoicePaymentsRouter from "./invoice-payments";
import publicInvoicesRouter from "./public-invoices";
import analyticsRouter from "./analytics";
import assistantRouter from "./assistant";
import usageRouter from "./usage";
import leadsRouter from "./leads";
import publicLeadsRouter from "./public-leads";
import publicReviewsRouter from "./public-reviews";
import publicQuoteFollowupsRouter from "./public-quote-followups";
import quickbooksRouter from "./quickbooks";
import waveRouter from "./wave";
import calendarRouter from "./calendar";
import emailConnectionsRouter from "./email-connections";
import securityRouter from "./security";
import importsRouter from "./imports";
import financeitRouter from "./financeit";
import flinksRouter from "./flinks";
import metaLeadAdsRouter from "./meta-lead-ads";
import googleLsaRouter from "./google-lsa";
import developerApiRouter from "./developer-api";
import publicV1Router from "./public-v1";
import archiveRouter from "./archive";
import accountRouter from "./account";
import smsRouter from "./sms";
import scheduleRouter from "./schedule";
import portalRouter from "./portal";
import clientPortalRouter from "./client-portal";
import pushRouter from "./push";

const router: IRouter = Router();

router.use(healthRouter);
router.use(quotesRouter);
router.use(businessProfileRouter);
router.use(paymentsRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(catalogRouter);
router.use(whatsappRouter);
router.use(clientsRouter);
router.use(documentsRouter);
router.use(crmRouter);
router.use(supportRouter);
router.use(publicQuotesRouter);
router.use(speechRouter);
router.use(cronRouter);
router.use(notificationsRouter);
router.use(contractsRouter);
router.use(signRouter);
router.use(jobsRouter);
router.use(costsRouter);
router.use(teamRouter);
router.use(teamMembersRouter);
router.use(workerTimeRouter);
router.use(crewRouter);
router.use(complianceRouter);
router.use(booksRouter);
router.use(invoicesRouter);
router.use(invoicePaymentsRouter);
router.use(publicInvoicesRouter);
router.use(analyticsRouter);
router.use(assistantRouter);
router.use(usageRouter);
router.use(leadsRouter);
router.use(publicLeadsRouter);
router.use(publicReviewsRouter);
router.use(publicQuoteFollowupsRouter);
router.use(quickbooksRouter);
router.use(waveRouter);
router.use(calendarRouter);
router.use(emailConnectionsRouter);
router.use(securityRouter);
router.use(importsRouter);
router.use(financeitRouter);
router.use(flinksRouter);
router.use(metaLeadAdsRouter);
router.use(googleLsaRouter);
router.use(developerApiRouter);
router.use(archiveRouter);
router.use(accountRouter);
router.use(smsRouter);
router.use(scheduleRouter);
router.use(portalRouter);
router.use(clientPortalRouter);
router.use(pushRouter);
router.use("/v1/public", publicV1Router);

export default router;
