import { Router, type IRouter } from "express";
import healthRouter from "./health";
import quotesRouter from "./quotes";
import businessProfileRouter from "./business-profile";
import paymentsRouter from "./payments";
import storageRouter from "./storage";
import adminRouter from "./admin";
import catalogRouter from "./catalog";
import whatsappRouter from "./whatsapp";
import clientsRouter from "./clients";
import documentsRouter from "./documents";
import crmRouter from "./crm";
import supportRouter from "./support";
import publicQuotesRouter from "./public-quotes";
import speechRouter from "./speech";
import cronRouter from "./cron";
import notificationsRouter from "./notifications";
import contractsRouter from "./contracts";
import signRouter from "./sign";
import jobsRouter from "./jobs";
import costsRouter from "./costs";
import teamRouter from "./team";
import teamMembersRouter from "./team-members";
import workerTimeRouter from "./worker-time";
import invoicesRouter from "./invoices";
import publicInvoicesRouter from "./public-invoices";
import analyticsRouter from "./analytics";
import assistantRouter from "./assistant";
import usageRouter from "./usage";
import leadsRouter from "./leads";
import publicLeadsRouter from "./public-leads";

const router: IRouter = Router();

router.use(healthRouter);
router.use(quotesRouter);
router.use(businessProfileRouter);
router.use(paymentsRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(catalogRouter);
router.use(whatsappRouter);
router.use(clientsRouter);
router.use(documentsRouter);
router.use(crmRouter);
router.use(supportRouter);
router.use(publicQuotesRouter);
router.use(speechRouter);
router.use(cronRouter);
router.use(notificationsRouter);
router.use(contractsRouter);
router.use(signRouter);
router.use(jobsRouter);
router.use(costsRouter);
router.use(teamRouter);
router.use(teamMembersRouter);
router.use(workerTimeRouter);
router.use(invoicesRouter);
router.use(publicInvoicesRouter);
router.use(analyticsRouter);
router.use(assistantRouter);
router.use(usageRouter);
router.use(leadsRouter);
router.use(publicLeadsRouter);

export default router;
