// Copies the design data from docs/pocket-design/handoff into src/theme, unchanged:
// tokens.ts, icons.json, tones.json, and the stand-alone SVGs (tab icons, orb, logo) as
// strings in svgs.ts. Run `npm run sync:design` after the handoff is regenerated; never
// edit these files by hand. src/theme is the only place colour values may appear (lint:tokens).
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const handoff = join(root, "..", "..", "docs", "pocket-design", "handoff");
const out = join(root, "src", "theme");
mkdirSync(out, { recursive: true });

const NOTE = "// Generated by scripts/sync-design.mjs from docs/pocket-design/handoff. Don't edit; re-run the script.\n";
writeFileSync(join(out, "tokens.ts"), NOTE + readFileSync(join(handoff, "tokens", "tokens.ts"), "utf8"));
writeFileSync(join(out, "icons.json"), readFileSync(join(handoff, "icons", "icons.json"), "utf8"));
writeFileSync(join(out, "tones.json"), readFileSync(join(handoff, "icons", "tones.json"), "utf8"));

const SVGS = { orb: "assistant-orb", logo: "logo", tabHome: "tab-home", tabQuotes: "tab-quotes", tabJobs: "tab-jobs", tabClients: "tab-clients" };
const clean = (s) => s.replace(/<metadata>[\s\S]*?<\/metadata>/g, "").replace(/\s*xmlns:c2pa="[^"]*"/g, "").trim();
const body = Object.entries(SVGS)
  .map(([k, f]) => `  ${k}: ${JSON.stringify(clean(readFileSync(join(handoff, "icons", `${f}.svg`), "utf8")))},`)
  .join("\n");
writeFileSync(join(out, "svgs.ts"), `${NOTE}export const svgs = {\n${body}\n} as const;\n`);
rmSync(join(out, "svg"), { recursive: true, force: true });
console.log("sync:design: tokens.ts, icons.json, tones.json, svgs.ts");
